spring:
  application:
    name: userface

server:
  port: 8000
# 注册中心配置
eureka:
  client:
    service-url:
      defaultZone: http://vm1:8761/eureka/
    enabled: true
    register-with-eureka: true
    fetch-registry: true
  instance:
    instance-id: 192.168.3.6:${server.port}
    ip-address: 192.168.3.8
    prefer-ip-address: true
